image: Ubuntu1804 #образ для сборки
stack: node 12 # окружение
branches: 
   only:
   - master # ветка git 
  chace: node-modules # кеширование
  install:
   - npm install # команда установки зависимостей
  build: off
  test_script:
   - npm run list && npm test # скрипт сборки